name: palspace_backend
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  isar: ^3.0.5
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  crypt: ^4.2.1
  darq: ^1.2.1
  dotenv: ^4.1.0
  mailer: ^6.0.0
  minio_new: ^1.0.2
  uuid: ^3.0.7
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
